### ISSUE TITLE
Segfault when HTTPS Inspection enabled [x64 Linux version]

### ISSUE THREAD

**Issue by SebastianMpl** [jingjingxyk/build-static-privoxy#1]
Hello,

Thank you very much for static version of provoxy. Works fine for me.
The only thing I have a problem is when I use HTTPS inspection.
When I set up certificates according to config file section about https inspection, add cert to a browser and enable https-inspection somewhere in the beginning of user.action to match all ( / ) after I  visit a website with https the application crashes with segmentation fault. If I change / to a specific website privoxy segfaults when visiting this particular website. Certs for websites are generated properly.
Do you use HTTPS Inspection? Could you please advice?

Thank you

**Comment by jingjingxyk** [comment]
@SebastianMpl 
I don't use https inspectiong .

Please provide an verification example .

我不使用 https inspect 
请提供一个验证例子
静态编译配置文件：
static link config:  https://github.com/jingjingxyk/static-privoxy/blob/main/sapi/src/builder/library/privoxy.php

**Comment by SebastianMpl** [comment]
@jingjingxyk 
Thank you for your reply. 
As an example it requires generating ssl certificates based on https inspection configuration and adding certificate to a browser.
In user.action file right after the definition of various aliases I have:
```
{+https-inspection}
/
```
to match all domains.

I'm not sure is it the right place for that declaration, so I will play a little more with it later

Anyway, thank you for providing static version of privoxy, and for providing the build config file.
Also please consider building privoxy static with mbedtls in some future time.
